// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXL85azA8igOgreLYNunwU0R2sLVVEUss',
    appId: '1:811327847815:web:498911a6d88bdec40fa722',
    messagingSenderId: '811327847815',
    projectId: 'clothes-renting-project',
    authDomain: 'clothes-renting-project.firebaseapp.com',
    storageBucket: 'clothes-renting-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3clK_zRN71JyGdsdRb-gLuLPP8ibX1M',
    appId: '1:811327847815:android:02c326fa0cbc15e80fa722',
    messagingSenderId: '811327847815',
    projectId: 'clothes-renting-project',
    storageBucket: 'clothes-renting-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5CwBfIk6I1CVAQJm3srmDUoP_jLnWHU',
    appId: '1:811327847815:ios:5f3d4c9e3490027c0fa722',
    messagingSenderId: '811327847815',
    projectId: 'clothes-renting-project',
    storageBucket: 'clothes-renting-project.appspot.com',
    iosClientId: '811327847815-fpa5mr440vrpl863k2ojuuof970edejh.apps.googleusercontent.com',
    iosBundleId: 'rent.clothes.clothesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5CwBfIk6I1CVAQJm3srmDUoP_jLnWHU',
    appId: '1:811327847815:ios:5f3d4c9e3490027c0fa722',
    messagingSenderId: '811327847815',
    projectId: 'clothes-renting-project',
    storageBucket: 'clothes-renting-project.appspot.com',
    iosClientId: '811327847815-fpa5mr440vrpl863k2ojuuof970edejh.apps.googleusercontent.com',
    iosBundleId: 'rent.clothes.clothesapp',
  );
}
